### ISSUE TITLE
.rom's from 128K doesn't load

### ISSUE THREAD

**Issue by old-delab** [dcrespo3d/ZX-ESPectrum-Wiimote#5]
I tried to replicate your wonderful project on a Lolin 32 Lite board, but the .rom's from 128K doesn't load (everything goes back to 48K mode). In 48K mode, everything is fine. What can be done?

**Comment by abelykh0** [comment]
Does Lolin 32 Lite board have PSRAM?

**Comment by DrNorfolk** [comment]
I will describe this problem here for someone in the future.
Lolin 32 is based on a wroom-32 chip that has no PSRAM memory.
To work with 128kb of firmware, you need a chip WROVER that has PSRAM memory

**Comment by DrNorfolk** [comment]
In continuation of this question.
I can't run ROMs PLUS3 and PLUS3E. The terminal says that everything was loaded successfully, but I only see a black screen.
```
Loading ROMSET '/rom/128K/PLUS3'
Getting entries from: '/rom/128K/PLUS3'
Found FILE: 0.rom...16384b...0.rom...ADDING
Found FILE: 1.rom...16384b...1.rom...ADDING
Found FILE: 2.rom...16384b...2.rom...ADDING
Found FILE: 3.rom...16384b...3.rom...ADDING
Processing 4 ROMs
Loading file '/rom/128K/PLUS3/0.rom'
Loading ROM '0.rom'
Loading file '/rom/128K/PLUS3/1.rom'
Loading ROM '1.rom'
Loading file '/rom/128K/PLUS3/2.rom'
Loading ROM '2.rom'
Loading file '/rom/128K/PLUS3/3.rom'
Loading ROM '3.rom'
Saving config file '/boot.cfg':
  + arch:128K
  + romset:PLUS3
  + ram:none
  + slog:true
  + asp169:true
Config saved OK
```
At first I thought the problem was that PLUS3 and PLUS3E are four parts (0.rom, 1.rom, 2.rom, 3.rom ), while SINCLAIR and PLUS2A are two parts (only 0.rom, 1 .rom).
But I tried adding PENTAGON128 ROM and it works. It consists of files 128p-0.rom, 128p-1.rom and trdos.rom. I renamed them to 0.rom, 1.rom, 2.rom. In general, this works, except for the trdos.rom part. It would be very interesting to see this in action.
Has anyone encountered such a problem?
Thank you!

**Comment by dcrespo3d** [comment]
I have removed PLUS3 and PLUS3E. I inherited them from original fork and they never worked. Probably, a disk controller emulation is needed, and I do not have plans on implementing it.

**Comment by old-delab** [comment]
I recommend a program for a TV set-top box on Android — ZX Spectrum Emulator.
Everything works perfectly and is compatible and cheap, and with the Internet!
